// <auto-generated />
using System;
using Kolokwium_30_06_2024_w66049.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kolokwium_30_06_2024_w66049.Migrations
{
    [DbContext(typeof(KolokwiumDbContext))]
    [Migration("20240630065845_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Kolokwium_30_06_2024_w66049.Data.DruzynaPilkarska", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Aktywny")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.ToTable("DruzynyPilkarskie", "KolokwiumAPIDb");
                });

            modelBuilder.Entity("Kolokwium_30_06_2024_w66049.Data.Mecz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("AnulowanyMecz")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("DataMeczu")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Druzyna1Id")
                        .HasColumnType("int");

                    b.Property<int>("Druzyna2Id")
                        .HasColumnType("int");

                    b.Property<int>("DruzynaPilkarska1Id")
                        .HasColumnType("int");

                    b.Property<int>("DruzynaPilkarska2Id")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("GodzinaMeczuDo")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("GodzinaMeczuOd")
                        .HasColumnType("time");

                    b.Property<string>("NazwaRozgrywki")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("DruzynaPilkarska1Id");

                    b.HasIndex("DruzynaPilkarska2Id");

                    b.ToTable("Mecze", "KolokwiumAPIDb");
                });

            modelBuilder.Entity("Kolokwium_30_06_2024_w66049.Data.Mecz", b =>
                {
                    b.HasOne("Kolokwium_30_06_2024_w66049.Data.DruzynaPilkarska", "DruzynaPilkarska1")
                        .WithMany()
                        .HasForeignKey("DruzynaPilkarska1Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kolokwium_30_06_2024_w66049.Data.DruzynaPilkarska", "DruzynaPilkarska2")
                        .WithMany()
                        .HasForeignKey("DruzynaPilkarska2Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DruzynaPilkarska1");

                    b.Navigation("DruzynaPilkarska2");
                });
#pragma warning restore 612, 618
        }
    }
}
